label_dtypes = {
    'DBP': float,
    'SBP': float,
    'ethnicity1': float,
    'Cornell criteria': float,
    'SL criteria value': float,
    'region': str,
    'country': str,
    'hcmDiag': float,
    'unctlHTN': float,
    'hcmdtunk': float,
    'holdtunk': float,
    'echdtunk': float,
    'ettdtunk': float,
    'ecgdtunk': float,
    'hxfamid2': str,
    'hxfamid3': str,
    'hxfamid4': str,
    'hxscd1st': float,
    'blothr': str,
    'blothrsp': str,
    'cmrmri': float,
    'cmrdt': str,
    'cmrgiv': float,
    'cmrdose': float,
    'cmrkitid': float,
    'cmrblood': float,
    'NTproBNP': float,
    'icf2method': float,
    'eoswith': str,
    'eosdt': str,
    'siteRegion': str,
    'siteCountry': str,
    'fu1visit': float,
    'fu1nyha': float,
    'fu1causdeat': float,
    'fu1alvendno': float,
    'fu2nyha': float,
    'fu2causdeat': float,
    'fu2alvendno': float,
    'fu3nyha': float,
    'fu3causdeat': float,
    'fu3alvendno': float,
    'fu3vtvfendno_3': float,
    'fu4nyha': float,
    'fu4causdeat': float,
    'fu4alvendno': float,
    'fu4txpendno': float,
    'fu4lvadendno': float,
    'fu4afiendno_5': float,
    'fu5nyha': float,
    'fu5causdeat': float,
    'fu6nyha': float,
    'fu6causdeat': float,
    'fu6icdshk': float,
    'fu6breath': float,
    'fu7nyha': float,
    'fu7causdeat': float,
    'FieldStrength': float,
    # 'Unnamed: 30': float,
    # 'Unnamed: 31': float,
    # 'Unnamed: 32': float,
    # 'Unnamed: 33': float,
    # 'Unnamed: 34': float,
    # 'Unnamed: 35': float,
    # 'Unnamed: 36': float,
    # 'Unnamed: 37': float,
    # 'Unnamed: 38': float,
    # 'Unnamed: 39': float,
    # 'Unnamed: 40': float,
    # 'Unnamed: 41': float,
    # 'Unnamed: 42': float,
    # 'Unnamed: 43': float,
    # 'Unnamed: 44': float,
    # 'Unnamed: 45': float,
    # 'Unnamed: 46': float,
    # 'Unnamed: 47': float,
    # 'Unnamed: 48': float,
    # 'Unnamed: 49': float,
    # 'Unnamed: 50': float,
    # 'Unnamed: 51': float,
    # 'Unnamed: 52': float,
    # 'Unnamed: 53': float,
    # 'Unnamed: 54': float,
    # 'Unnamed: 55': float,
    # 'Unnamed: 56': float,
    # 'Unnamed: 57': float,
    # 'Unnamed: 58': float,
    # 'Unnamed: 59': float,
    # 'Unnamed: 60': float,
    # 'Unnamed: 61': float,
    'max_LVOT_grad_group': float,
    'MR_severity': float,
    'BP_meds': float,
    'fhx_hcm_any': float,
    'hf_any': float,
    'af_any': float,
    'vt_any': float,
    'stroke_any': float,
    'log_max_LVOT_grad': float,
    'low_lvef': float
}
